version: '3.3'

services:
  api:
    container_name: project_api
    restart: unless-stopped
    build: 
      dockerfile: ./dockerfile
      context: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    command: npm run dev
    depends_on:
      - db
    links:
      - db
  db: 
    image: postgres:13.6-alpine
    container_name: project_db
    restart: unless-stopped
    volumes:
      - ./docker/postgres:/var/lib/postgresql
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}